apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  # Key-value pairs for configuration data
  log_level: INFO
  feature_flag_enabled: "true"
  database_url: "jdbc:postgresql://mydb.example.com:5432/myappdb"
  deployment_created_at: "Monday, 29 September 2025 4:07:39 pm"
